### ISSUE TITLE
Loading a glTF that already contains KTX assets

### ISSUE THREAD

**Issue by echadwick-artist** [KhronosGroup/glTF-Compressor#3]
1. Download the glTF and BIN and KTX2 from https://github.com/KhronosGroup/3D-Formats-Guidelines/tree/main/samples/Duck/glTF-KTX-ETC1S/
2. Go to https://phasmatic3d.github.io/glTF-Sample-Viewer-KTX-demo/
3. Drag and drop the files into the 3d view.
Result: an error message appears, and the "after" display is blackened (even though no compression has been initiated).
![image](https://github.com/KhronosGroup/glTF-Compressor/assets/40177036/79f43695-1ed0-4c8d-9fe5-9d7597299d22)

This bug might be related to
https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/473

**Comment by echadwick-artist** [comment]
Loading KTX assets as source files for recompression was probably not specified in the design for this tool. However it would still be helpful to be able to support this. 

Loading previously-compressed KTX assets could be useful for converting from KTX back to PNG and/or JPG. This is not a practice we want to encourage, but judging from existing user behavior with JPG remixing this is probably something users will want to be able to do.

Regardless of whether we want to support recompressing KTX assets, it could also be useful to be able to load an existing KTX compressed asset into glTF-Compressor to interrogate RAM costs and other data such as texture resolutions and channels in use.

**Comment by abasilak** [comment]
The commit https://github.com/phasmatic3d/glTF-Sample-Viewer-KTX/commit/17d21b6c314e59b8ee2bdf8920131c7e3dfae9e1 solved this issue.

**Comment by MarkCallow** [comment]
Loading compressed KTX assets for recompression is definitely not something we want to encourage. As glTF does not support using uncompressed KTX files, the useful feature of loading uncompressed KTX assets and compressing is not applicable.

Images can be extracted from a KTX file and saved to PNG with the new `ktx extract` tool in KTX-Software 4.3.

I agree it is useful to be able to load an existing KTX compressed asset in order to view the data.

**Comment by echadwick-artist** [comment]
Looks good thank you!
